import { ApiError, ChatApi, type ChatConfig, type ChatMessage } from './api.js';
import { SessionStorage } from './storage.js';

export type WidgetOptions = { workspaceId: string; siteId: string; apiUrl: string; mount?: HTMLElement };
const defaults: ChatConfig = { businessName: 'Website support', greeting: 'How can we help?', themeColor: '#6257e3', position: 'right', aiDisclosure: 'Replies may be AI-generated.' };

export class ZevrakoWidget {
  private readonly api: ChatApi; private readonly storage: SessionStorage; private readonly host: HTMLElement; private root!: ShadowRoot; private config = defaults; private token?: string; private conversationId?: string; private messages: ChatMessage[] = []; private timer?: number; private unread = 0;
  constructor(private readonly options: WidgetOptions) { this.api = new ChatApi(options.apiUrl.replace(/\/$/, ''), options.workspaceId, options.siteId); this.storage = new SessionStorage(`zevrako-chat:${options.workspaceId}:${options.siteId}`); this.host = options.mount ?? document.body.appendChild(document.createElement('div')); }
  async initialize() { this.root = this.host.shadowRoot ?? this.host.attachShadow({ mode: 'open' }); this.render(); try { this.config = await this.api.config(); this.render(); const restored = this.storage.load(); if (restored) { this.token = restored.token; this.conversationId = restored.conversationId; await this.refresh(); } } catch (e) { this.setStatus(this.safeMessage(e), true); } return this; }
  destroy() { if (this.timer) clearInterval(this.timer); this.host.remove(); }
  private render() { this.root.innerHTML = `<style>${styles(this.config)}</style><button class="launcher" aria-label="Open ${escapeHtml(this.config.businessName)} chat" aria-expanded="false"><span aria-hidden="true">✦</span><span class="badge" hidden>0</span></button><section class="panel" role="dialog" aria-label="${escapeHtml(this.config.businessName)} chat" hidden><header><div><strong>${escapeHtml(this.config.businessName)}</strong><small class="presence">Checking availability…</small></div><button class="close" aria-label="Close chat">×</button></header><main aria-live="polite"><section class="intro"><p>${escapeHtml(this.config.greeting)}</p><form class="identity"><label>Name<input name="name" maxlength="120" required autocomplete="name"></label><label>Email <span>(optional)</span><input name="email" type="email" maxlength="254" autocomplete="email"></label><button>Start chat</button></form></section><ol class="messages" aria-label="Message history"></ol><p class="typing" hidden>Support is typing…</p><p class="status" role="status"></p><button class="retry" hidden>Try again</button></main><form class="composer" hidden><label class="sr-only" for="zevrako-message">Message</label><textarea id="zevrako-message" maxlength="4000" rows="1" placeholder="Write a message…"></textarea><button aria-label="Send message">Send</button></form><footer>${escapeHtml(this.config.aiDisclosure)}</footer></section>`; this.bind(); }
  private bind() { const launcher = this.q<HTMLButtonElement>('.launcher'); const panel = this.q<HTMLElement>('.panel'); launcher.onclick = () => { panel.hidden = false; launcher.setAttribute('aria-expanded', 'true'); this.unread = 0; this.updateBadge(); this.q<HTMLInputElement>('input[name=name]')?.focus(); }; this.q<HTMLButtonElement>('.close').onclick = () => { panel.hidden = true; launcher.setAttribute('aria-expanded', 'false'); launcher.focus(); }; this.q<HTMLFormElement>('.identity').onsubmit = (event) => { event.preventDefault(); void this.start(new FormData(event.currentTarget as HTMLFormElement)); }; this.q<HTMLFormElement>('.composer').onsubmit = (event) => { event.preventDefault(); void this.send(); }; this.q<HTMLTextAreaElement>('.composer textarea').onkeydown = (event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void this.send(); } }; this.q<HTMLButtonElement>('.retry').onclick = () => void this.refresh(); }
  private async start(form: FormData) { this.setBusy(true); try { const session = await this.api.session(String(form.get('name')), String(form.get('email') ?? '')); const conversation = await this.api.conversation(session.token); this.token = conversation.token; this.conversationId = conversation.conversationId; this.storage.save({ token: conversation.token, conversationId: conversation.conversationId, expiresAt: Date.now() + 29 * 60_000 }); this.q<HTMLElement>('.intro').hidden = true; this.q<HTMLFormElement>('.composer').hidden = false; this.setStatus('Online'); this.beginPolling(); this.q<HTMLTextAreaElement>('.composer textarea').focus(); } catch (e) { this.setStatus(this.safeMessage(e), true); } finally { this.setBusy(false); } }
  private async send() { if (!this.token || !this.conversationId) return; const input = this.q<HTMLTextAreaElement>('.composer textarea'); const text = input.value.trim(); if (!text) return; const localId = crypto.randomUUID(); input.value = ''; this.messages.push({ id: localId, role: 'visitor', text, deliveryState: 'sending' }); this.renderMessages(); try { await this.api.send(this.token, this.conversationId, text, localId); const message = this.messages.find((m) => m.id === localId); if (message) message.deliveryState = 'delivered'; this.setStatus('Delivered'); } catch (e) { const message = this.messages.find((m) => m.id === localId); if (message) message.deliveryState = 'failed'; this.setStatus(this.safeMessage(e), true); } this.renderMessages(); }
  private async refresh() { if (!this.token || !this.conversationId) return; try { const was = this.messages.length; const result = await this.api.messages(this.token, this.conversationId); this.messages = merge(result.messages, this.messages.filter((m) => m.deliveryState === 'failed')); if (this.messages.length > was && this.q<HTMLElement>('.panel').hidden) { this.unread += this.messages.length - was; this.updateBadge(); } this.q<HTMLElement>('.intro').hidden = true; this.q<HTMLFormElement>('.composer').hidden = false; this.renderMessages(); this.setStatus(navigator.onLine ? 'Online' : 'Offline'); this.beginPolling(); } catch (e) { if (e instanceof ApiError && e.status === 401) this.storage.clear(); this.setStatus(this.safeMessage(e), true); } }
  private beginPolling() { if (this.timer) return; this.timer = window.setInterval(() => void this.refresh(), 4000); }
  private renderMessages() { this.q<HTMLOListElement>('.messages').innerHTML = this.messages.map((m) => `<li class="${m.role}"><span>${escapeHtml(m.text)}</span><small>${m.deliveryState}${m.deliveryState === 'failed' ? ' — retry by sending again' : ''}</small></li>`).join(''); }
  private updateBadge() { const badge = this.q<HTMLElement>('.badge'); badge.hidden = this.unread === 0; badge.textContent = String(this.unread); }
  private setBusy(value: boolean) { this.q<HTMLButtonElement>('.identity button').disabled = value; this.q<HTMLButtonElement>('.identity button').textContent = value ? 'Connecting…' : 'Start chat'; }
  private setStatus(text: string, error = false) { const status = this.q<HTMLElement>('.status'); status.textContent = text; status.classList.toggle('error', error); this.q<HTMLButtonElement>('.retry').hidden = !error; this.q<HTMLElement>('.presence').textContent = error ? 'Unavailable' : text; }
  private safeMessage(e: unknown) { if (e instanceof ApiError) return e.code === 'rate_limited' ? 'Too many messages. Please wait and try again.' : e.message; return navigator.onLine ? 'Chat is temporarily unavailable.' : 'You are offline. Check your connection.'; }
  private q<T extends Element>(selector: string) { return this.root.querySelector<T>(selector)!; }
}

function merge(remote: ChatMessage[], localFailed: ChatMessage[]) { const seen = new Set(remote.map((m) => m.id)); return [...remote, ...localFailed.filter((m) => !seen.has(m.id))]; }
function escapeHtml(value: string) { const node = document.createElement('span'); node.textContent = value; return node.innerHTML; }
function styles(config: ChatConfig) { return `:host,*{box-sizing:border-box}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}button,input,textarea{font:inherit}.launcher{position:fixed;${config.position}:20px;bottom:20px;width:58px;height:58px;border:0;border-radius:50%;background:${config.themeColor};color:white;font-size:25px;cursor:pointer;box-shadow:0 8px 28px #0003}.badge{position:absolute;right:-2px;top:-4px;background:#d52b45;border:2px solid white;border-radius:999px;min-width:23px;padding:2px;color:white;font-size:12px}.panel{position:fixed;${config.position}:20px;bottom:90px;width:min(390px,calc(100vw - 24px));height:min(620px,calc(100vh - 116px));background:#fff;color:#19202a;border-radius:18px;overflow:hidden;box-shadow:0 15px 60px #15213a40;font:14px/1.45 system-ui,sans-serif;z-index:2147483647;flex-direction:column}.panel:not([hidden]){display:flex}header{background:${config.themeColor};color:#fff;padding:16px;display:flex;justify-content:space-between;align-items:center}header small{display:block;opacity:.82}.close{border:0;background:transparent;color:white;font-size:28px;cursor:pointer}main{flex:1;overflow:auto;padding:18px;background:#f6f7fb}.intro{background:white;padding:16px;border-radius:12px}.identity label{display:block;margin:12px 0}.identity span{color:#687080}.identity input{display:block;width:100%;padding:10px;margin-top:4px;border:1px solid #ccd1dc;border-radius:8px}.identity button,.retry{border:0;border-radius:8px;padding:10px 14px;background:${config.themeColor};color:white;cursor:pointer}.messages{list-style:none;padding:0;margin:0;display:flex;flex-direction:column;gap:10px}.messages li{max-width:82%;display:flex;flex-direction:column}.messages li span{padding:10px 12px;border-radius:12px;background:white;white-space:pre-wrap;overflow-wrap:anywhere}.messages li.visitor{align-self:flex-end}.messages li.visitor span{background:${config.themeColor};color:white}.messages small{font-size:10px;color:#697181;margin-top:2px}.status{color:#526070}.status.error{color:#b3261e}.composer{display:flex;gap:8px;padding:12px;border-top:1px solid #e5e7ed}.composer textarea{flex:1;resize:none;border:1px solid #ccd1dc;border-radius:9px;padding:9px}.composer button{border:0;border-radius:9px;background:${config.themeColor};color:white;padding:0 15px}footer{text-align:center;font:11px system-ui;color:#687080;padding:0 12px 10px}@media(max-width:480px){.panel{inset:0;width:100vw;height:100dvh;max-height:none;border-radius:0}.launcher{right:14px;bottom:14px}}@media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;animation:none!important;transition:none!important}}` }
